### ISSUE TITLE
Imagenes para readme

### ISSUE THREAD

**Issue by HentaiIsPower** [Criptext/MonkeyUIAndroid#8]
![screenshot_2016-04-27-23-57-49](https://cloud.githubusercontent.com/assets/14115856/14875816/22e457e2-0cd4-11e6-8096-add2cd2a3f20.jpeg)

**Comment by GAumala** [comment]
![screenshot_2016-07-21-16-41-50](https://cloud.githubusercontent.com/assets/5729175/17040194/122a422c-4f64-11e6-89f7-0a0311988a58.jpeg)
